services:
  app:
    image: mcr.microsoft.com/vscode/devcontainers/javascript-node
    volumes:
      - ..:/workspace:cached
    ports:
      - "3000:3000"
      - "5000:5000"
    command: sleep infinity
